### ISSUE TITLE
Contribute initial version

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo-trs-consumer#1]
Needed steps are below.

**CQs**

- [ ] [j2bugzilla 2.2.1](https://mvnrepository.com/artifact/com.j2bugzilla/j2bugzilla/2.2.1) (code uses 2.2, last CQ is for [j2bugzilla 1.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=5970))

**Comment by berezovskyi** [comment]
@jamsden @jadelkhoury the code has headers for EPL 1.0 and EDL, but I never heard of EDL discussion before Sharon okayed it there. I am removing the EDL declarations from the source code that I will be pushing in a PR.

**Comment by jadelkhoury** [comment]
I thought all of Lyo stuff is both EDL and EPL. See for example org.eclipse.lyo.core\org.eclipse.lyo.oslc4j.core\license.
The generator also produces 2 license files.

**Comment by berezovskyi** [comment]
https://git.eclipse.org/r/#/c/101728/

**Comment by berezovskyi** [comment]
and on the EPL/EDL: all of Lyo stuff MUST be EPL & EDL unless we change it with the PMC. Don't have time to raise it now.

**Comment by berezovskyi** [comment]
so there is no action to remove anything from the headers

**Comment by berezovskyi** [comment]
Now I also need to fix the branch mess
